apiVersion: apps/v1
kind: Deployment
metadata:
  name: casino-backend-deployment
  namespace: default
  labels:
    app: casino-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: casino-backend
  template:
    metadata:
      labels:
        app: casino-backend
    spec:
      containers:
      - name: casino-backend
        image: casino-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"