apiVersion: v1
kind: Service
metadata:
  name: casino-backend-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: casino-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000